---
version: '3.8'
services:

  kafka-connect-cluster:
    image: landoop/fast-data-dev:latest
    container_name: kafka-connect-cluster
    ports:
      - "2181:2181"
      - "3030:3030"
      - "8081-8083:8081-8083"
      - "9581-9585:9581-9585"
      - "9092:9092"
    environment:
      ADV_HOST: 127.0.0.1
      RUNTESTS: 0

  es01-connect:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    volumes:
      - "es-data-es01-connect:/usr/share/elasticsearch/data"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: [ "CMD-SHELL", "curl http://localhost:9200" ]
      interval: 10s
      timeout: 10s
      retries: 120

volumes:
  es-data-es01-connect:
  kafka_data:
    driver: local